### ISSUE TITLE
Doesn't work if "ReadOnly = true" or "Editable = false"

### ISSUE THREAD

**Issue by netcop82** [DevExpress-Examples/how-to-use-the-layoutview-cardview-as-a-master-view-in-master-detail-mode-e2428#1]
This workaround is useless if I need a readonly layoutform. It only works on a layoutview that allows the end user to edit values; otherwise, the popup never shows.

**Comment by AlexGreenZ** [comment]
Hello,

If your goal is to make LayoutView non-editable or read-only, you can handle the [LayoutView.ShowingEditor](https://docs.devexpress.com/WindowsForms/DevExpress.XtraGrid.Views.Base.ColumnView.ShowingEditor) event and allow editing only for the Detail column as follows:

```cs
private void layoutView1_ShowingEditor(object sender, CancelEventArgs e)
{
    LayoutView view = (LayoutView)sender;
    if (view.FocusedColumn.FieldName != "Detail")
        e.Cancel = true;
}
```

If you have additional questions, it is better to create a new ticket in our [Support Center](www.devexpress.com/support/center). Feel free to describe your scenario in greater detail. This information will allow us to find a suitable solution faster.
